DROP TABLE IF EXISTS tasks;

CREATE TABLE tasks (
	id SERIAL PRIMARY KEY,
	title VARCHAR(255) NOT NULL,
	status VARCHAR(20) NOT NULL DEFAULT 'NOT_STARTED'
	    CHECK (status IN ('NOT_STARTED', 'COMPLETED', 'TRASHED')),
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
	updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now()
);
