DROP TABLE IF EXISTS tasks;
DROP TYPE IF EXISTS task_status;

CREATE TYPE task_status AS ENUM (
	'NOT_STARTED',
	'COMPLETED',
	'TRASHED'
);

CREATE TABLE tasks (
	id UUID PRIMARY KEY,
	title VARCHAR(255) NOT NULL,
	status task_status NOT NULL DEFAULT 'NOT_STARTED',
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
	updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now()
);
